### ISSUE TITLE
Running through Docker has certain pages missing layout

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/molgenis-app-vibe#29]
After following [these steps](https://github.com/molgenis/molgenis-app-vibe/tree/3384904a3a8c506664f47b029deaa03306d531ab#create-local-test-environment) to run molgenis-app-vibe through docker, certain webpages seem to missing their layout while others aren't. Steps 5 & 6 do not influence this (see also the Static content config page screenshot that doesn't have correct layout either).

### Homepage:
![Schermafbeelding 2021-04-19 om 14 10 14](https://user-images.githubusercontent.com/7658246/115235664-b8685900-a11a-11eb-8d71-af8cee2af75c.png)

### Data explorer:
![Schermafbeelding 2021-04-19 om 14 10 45](https://user-images.githubusercontent.com/7658246/115235682-be5e3a00-a11a-11eb-80bb-91940c955928.png)

### Static content config page:
![Schermafbeelding 2021-04-19 om 14 11 05](https://user-images.githubusercontent.com/7658246/115235700-c4541b00-a11a-11eb-9bb6-993c713a8725.png)

# Stacktrace:
```
molgenis_1       | 2021-04-19_12:20:45.590 [http-nio-8080-exec-1] WARN  io.sentry.dsn.Dsn - *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/ ***
molgenis_1       | 2021-04-19_12:20:51.846 [http-nio-8080-exec-5] ERROR freemarker.runtime - Error executing FreeMarker template part in the #attempt block
molgenis_1       | freemarker.core._TemplateModelException: Java method "org.molgenis.core.ui.style.ThemeFingerprintRegistry.getFingerprint(String)" threw an exception when invoked on org.molgenis.core.ui.style.ThemeFingerprintRegistry object "org.molgenis.core.ui.style.ThemeFingerprintRegistry@1ed6d472"; see cause exception in the Java stack trace.
molgenis_1       | 
molgenis_1       | ----
molgenis_1       | FTL stack trace ("~" means nesting-related):
molgenis_1       | 	- Failed at: ${theme_fingerprint_registry.getFinge...  [in template "theme-macros.ftl" in macro "theme_href" at line 3, column 160]
molgenis_1       | 	- Reached through: @theme_href "/css/bootstrap-4/${app_s...  [in template "molgenis-header.ftl" in macro "header" at line 61, column 38]
molgenis_1       | 	- Reached through: @header css=[] js=[] version=2  [in template "view-staticcontent.ftl" at line 4, column 1]
molgenis_1       | ----
molgenis_1       | 	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
molgenis_1       | 	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
molgenis_1       | 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:77)
molgenis_1       | 	at freemarker.core.MethodCall._eval(MethodCall.java:65)
molgenis_1       | 	at freemarker.core.Expression.eval(Expression.java:83)
molgenis_1       | 	at freemarker.core.BuiltInForLegacyEscaping._eval(BuiltInForLegacyEscaping.java:33)
molgenis_1       | 	at freemarker.core.Expression.eval(Expression.java:83)
molgenis_1       | 	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
molgenis_1       | 	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:336)
molgenis_1       | 	at freemarker.core.Environment.visitAttemptRecover(Environment.java:549)
molgenis_1       | 	at freemarker.core.AttemptBlock.accept(AttemptBlock.java:45)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:372)
molgenis_1       | 	at freemarker.core.Environment.invoke(Environment.java:775)
molgenis_1       | 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:372)
molgenis_1       | 	at freemarker.core.Environment.invoke(Environment.java:775)
molgenis_1       | 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:336)
molgenis_1       | 	at freemarker.core.Environment.process(Environment.java:309)
molgenis_1       | 	at freemarker.template.Template.process(Template.java:384)
molgenis_1       | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:389)
molgenis_1       | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:302)
molgenis_1       | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:253)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:178)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1370)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1116)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
molgenis_1       | 	at org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequestDispatcher.forward(HeaderWriterFilter.java:143)
molgenis_1       | 	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:170)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1370)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1116)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
molgenis_1       | 	at org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequestDispatcher.forward(HeaderWriterFilter.java:143)
molgenis_1       | 	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:170)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1370)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1116)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:108)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
molgenis_1       | 	at org.molgenis.security.twofactor.auth.TwoFactorAuthenticationFilter.doFilterInternal(TwoFactorAuthenticationFilter.java:54)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.molgenis.security.MolgenisChangePasswordFilter.doFilter(MolgenisChangePasswordFilter.java:52)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
molgenis_1       | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.molgenis.security.token.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:52)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:160)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
molgenis_1       | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
molgenis_1       | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.molgenis.core.ui.browserdetection.BrowserDetectionFilter.doFilter(BrowserDetectionFilter.java:52)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
molgenis_1       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
molgenis_1       | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
molgenis_1       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
molgenis_1       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
molgenis_1       | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
molgenis_1       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
molgenis_1       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
molgenis_1       | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
molgenis_1       | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
molgenis_1       | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
molgenis_1       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
molgenis_1       | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
molgenis_1       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
molgenis_1       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
molgenis_1       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
molgenis_1       | 	at java.base/java.lang.Thread.run(Thread.java:834)
molgenis_1       | Caused by: java.io.UncheckedIOException: java.io.FileNotFoundException: /home/molgenis/data/filestore/aaaac6hjfxp7yascvqjqabaaae
molgenis_1       | 	at org.molgenis.core.ui.style.StyleServiceImpl.getThemeData(StyleServiceImpl.java:176)
molgenis_1       | 	at org.molgenis.core.ui.style.StyleServiceImpl$$FastClassBySpringCGLIB$$453caac0.invoke(<generated>)
molgenis_1       | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
molgenis_1       | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
molgenis_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
molgenis_1       | 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
molgenis_1       | 	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:38)
molgenis_1       | 	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:20)
molgenis_1       | 	at jdk.internal.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
molgenis_1       | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
molgenis_1       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
molgenis_1       | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
molgenis_1       | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
molgenis_1       | 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
molgenis_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
molgenis_1       | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
molgenis_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
molgenis_1       | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
molgenis_1       | 	at org.molgenis.core.ui.style.StyleServiceImpl$$EnhancerBySpringCGLIB$$65a0fe9.getThemeData(<generated>)
molgenis_1       | 	at org.molgenis.core.ui.style.ThemeFingerprintRegistry.createFingerprint(ThemeFingerprintRegistry.java:40)
molgenis_1       | 	at org.molgenis.core.ui.style.ThemeFingerprintRegistry.getFingerprint(ThemeFingerprintRegistry.java:31)
molgenis_1       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
molgenis_1       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
molgenis_1       | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
molgenis_1       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
molgenis_1       | 	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
molgenis_1       | 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
molgenis_1       | 	... 160 common frames omitted
molgenis_1       | Caused by: java.io.FileNotFoundException: /home/molgenis/data/filestore/aaaac6hjfxp7yascvqjqabaaae
molgenis_1       | 	at org.molgenis.data.file.FileStore.getFile(FileStore.java:82)
molgenis_1       | 	at org.molgenis.core.ui.style.StyleServiceImpl.getThemeData(StyleServiceImpl.java:174)
molgenis_1       | 	... 186 common frames omitted
```

**Comment by svandenhoek** [comment]
Issue can be solved by running `docker system prune` and then running `docker-compose up --force-recreate --build` again.

**Comment by svandenhoek** [comment]
README is updated with workaround in #30.
